### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by mxtilx** [jie65535/JGrasscutterCommand#1]
[1.txt](https://github.com/jie65535/JGrasscutterCommand/files/9484286/1.txt)

**Comment by jie65535** [comment]
`http://43...:15145` 这个地址是你自己打码的吗？请确认输入的地址是正确的

**Comment by mxtilx** [comment]
> 

43.248.96.191
确定是正确的

**Comment by jie65535** [comment]
需要指定的是HTTP的端口，不是游戏的端口，可以看看服务端配置文件关于HTTP的部分吗

**Comment by mxtilx** [comment]
> 
"http": {
      "bindAddress": "0.0.0.0",
      "bindPort": 15142,
      "accessAddress": "43.",
      "accessPort": 0,
      "encryption": {
        "useEncryption": true,
        "useInRouting": true,
        "keystore": "./keystore.p12",
        "keystorePassword": "123456"

**Comment by mxtilx** [comment]
> > 
> 
> "http": { "bindAddress": "0.0.0.0", "bindPort": 15142, "accessAddress": "43.248.96.191", "accessPort": 0, "encryption": { "useEncryption": true, "useInRouting": true, "keystore": "./keystore.p12", "keystorePassword": "123456"

**Comment by jie65535** [comment]
> "useEncryption": true, "useInRouting": true

你开了HTTPS，地址也要改成https才可以

**Comment by mxtilx** [comment]
> > "useEncryption": true, "useInRouting": true
> 
> 你开了HTTPS，
[2.txt](https://github.com/jie65535/JGrasscutterCommand/files/9484339/2.txt)
地址也要改成https才可以

**Comment by jie65535** [comment]
噢，是证书问题，你先关闭https模式，用http来访问
`useEncryption": false, "useInRouting": false`

晚点我会修复
