### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by PDMengQAQ** [jie65535/JGrasscutterCommand#10]
不在线好像就没有办法执行命令了(admin也是) 还有就是重启服务器过后就需要重新绑定uid

**Comment by jie65535** [comment]
因为OpenCommand插件没有持久化发放的令牌，所以重启服务器就重置了，得重新验证。

因为现在(v0.4)增加了管理员命令，所以原来的直接执行命令改成了优先以玩家身份执行，所以管理员不在线也没法执行，得用op前缀。

你还可以设置一些公开命令，默认是以控制台令牌执行的，不用绑定。

**Comment by jie65535** [comment]
关于 [OpenCommand](https://github.com/jie65535/gc-opencommand-plugin) 插件持久化Token的问题，可以[提一个Issue](https://github.com/jie65535/gc-opencommand-plugin/issues/new)

**Comment by jie65535** [comment]
我打开了一个 [Issue](https://github.com/jie65535/gc-opencommand-plugin/issues/19)，你可以关注它以在我实现后立刻尝试。

**Comment by PDMengQAQ** [comment]
你好，op前缀是指!op+命令吗 我原本是想用两个机器人实现自动开服的 我自己的插件写好了发现了这么个问题 请问能修复吗
另外 管理员是否无需绑定uid 直接使用!执行命令呢 还是说就是前面所说的“op前缀”
感谢解答！麻烦了！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月5日(星期三) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jie65535/JGrasscutterCommand] 一些问题 (Issue #10)





 
因为OpenCommand插件没有持久化发放的令牌，所以重启服务器就重置了，得重新验证。
 
因为现在(v0.4)增加了管理员命令，所以原来的直接执行命令改成了优先以玩家身份执行，所以管理员不在线也没法执行，得用op前缀。
 
你还可以设置一些公开命令，默认是以控制台令牌执行的，不用绑定。

**Comment by jie65535** [comment]
参见README，管理员可以直接`op give...`不需要绑定也可以执行，前提是你设置了账号为管理员，并且你设置了控制台令牌。

基本上就是把 `!` 改成 `op` ，就是以控制台身份执行。

**Comment by PDMengQAQ** [comment]
ok 感谢您的解答 麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月5日(星期三) 晚上8:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jie65535/JGrasscutterCommand] 一些问题 (Issue #10)





 
参见README，管理员可以直接op give...不需要绑定也可以执行。

**Comment by jie65535** [comment]
我更新了 OpenCommand 插件，现在它可以持久化生成的令牌，这样重启也不会需要重新绑定了。
https://github.com/jie65535/gc-opencommand-plugin/releases/tag/v1.5.0
