### ISSUE TITLE
[问题] 设置非好友为管理员时报错

### ISSUE THREAD

**Issue by mxtilx** [jie65535/JGrasscutterCommand#11]
administrator添加失败
> /jgc setAdmin 1580492284
2022-10-05 22:12:32 W/console: 无法推断目标好友或群员.
- 机器人号码.群号码.群员号码
- 机器人号码.群号码.群员名片   (模糊搜索)
- ~   (指代指令调用人自己. 仅聊天环境下)
- 机器人号码.群号码.$   (随机成员)
- 机器人号码.好友号码

当处于一个群内时，机器人号码和群号码参数都可省略
当只登录了一个机器人时，机器人号码可省略
这个QQ号码是另外一个群主的
![Screenshot_2022-10-05-22-16-24-83](https://user-images.githubusercontent.com/96869052/194084015-c3b6be85-cabf-440f-b8a3-eabe5c03a731.jpg)
![Screenshot_2022-10-05-22-16-45-63](https://user-images.githubusercontent.com/96869052/194084046-c02fd436-df92-43eb-8f9f-c591302093be.jpg)

**Comment by jie65535** [comment]
`/jgc setAdmin 群号.QQ号`
