### ISSUE TITLE
群聊消息同步无法使用

### ISSUE THREAD

**Issue by lniuua** [jie65535/JGrasscutterCommand#12]
开启群聊消息同步后，会显示名字但是无法显示消息
![image](https://user-images.githubusercontent.com/105270768/194259716-5d25587e-8e48-461b-80b4-156cac06cf82.png)

我的：Grasscutter版本 1.3.2

我的：JGrasscutterCommand版本 v0.300

**Comment by jie65535** [comment]
该问题已经在v0.4.0解决，现在已经是预发布状态，你可以在[这里下载](https://github.com/jie65535/JGrasscutterCommand/releases)。
