### ISSUE TITLE
Hello, do you want to support other robot frameworks?

### ISSUE THREAD

**Issue by wcjqwq** [jie65535/JGrasscutterCommand#2]
Hello developers, I think I have a question. Do you plan to support some robot frameworks? (https://www.bilibili.com/read/cv10629769) If you don't think so, just pretend I didn't say it.
I recommend https://drea.cc

**Comment by wcjqwq** [comment]
我不是很推荐在的QQ群里面发信息（容易造成信息过多

**Comment by jie65535** [comment]
- 目前暂无支持其它机器人框架的计划
- 设计时我也想过私聊使用机器人，主要考虑到如果绑定多个服务器操作比较麻烦，就懒得写了，后面可能考虑增加私聊使用的功能。

**Comment by wcjqwq** [comment]
我个人更推荐私聊（方便注册账号）

**Comment by sj817** [comment]
其实可以使用yunzai的机器人，已插件的方式在云崽上面运行
