### ISSUE TITLE
[功能] 私聊执行命令

### ISSUE THREAD

**Issue by jie65535** [jie65535/JGrasscutterCommand#3]
# 描述
允许玩家私聊机器人来绑定或执行命令

# 实现方式
增加一个默认服务器的配置，私聊执行将使用默认服务器进行。

# 扩展
默认服务器的设定可用于绑定或启用群
- 当在某个未绑定群启用时，自动将其绑定到默认服务器
- 当在某个群使用绑定群命令时，允许忽略服务器id参数，这将使用默认服务器替代

**Comment by wcjqwq** [comment]
👀

**Comment by jie65535** [comment]
已在 v0.3.0 中实现
