### ISSUE TITLE
[功能] 区分管理员执行命令权限

### ISSUE THREAD

**Issue by mxtilx** [jie65535/JGrasscutterCommand#7]
![Screenshot_2022-09-18-20-36-13-21](https://user-images.githubusercontent.com/96869052/190902432-987137fb-6206-4669-a38b-5f48684fc448.jpg)

**Comment by jie65535** [comment]
因为管理员默认是使用控制台命令执行的，因此管理员绑定没有效果，此处可能需要设计如何区分管理员使用哪一种身份。

**Comment by jie65535** [comment]
此外，还应该设计别名允许传参或指定目标。

**Comment by jie65535** [comment]
https://github.com/jie65535/JGrasscutterCommand/releases/tag/v0.4.0

现已发布更新，邀请您协助测试新版本功能，并将测试结果在下方回复，谢谢！

**Comment by mxtilx** [comment]
> https://github.com/jie65535/JGrasscutterCommand/releases/tag/v0.4.0
> 
> 现已发布更新，邀请您协助测试新版本功能，并将测试结果在下方回复，谢谢！

才看到抱歉

**Comment by mxtilx** [comment]
> https://github.com/jie65535/JGrasscutterCommand/releases/tag/v0.4.0
> 
> 现已发布更新，邀请您协助测试新版本功能，并将测试结果在下方回复，谢谢！

![Screenshot_2022-10-05-22-38-13-46](https://user-images.githubusercontent.com/96869052/194088571-d184b257-842e-41b0-a7ba-740913f67d59.jpg)

**Comment by jie65535** [comment]
发布里已经说了，默认前缀 `!` 是以用户身份，新增加了一个前缀 `op` 来表示管理员执行。

**Comment by mxtilx** [comment]
> 发布里已经说了，默认前缀 `!` 是以用户身份，新增加了一个前缀 `op` 来表示管理员执行。

为什么按回车前和后的内容不一致
![Screenshot_2022-10-05-22-59-40-92](https://user-images.githubusercontent.com/96869052/194094292-c329ee54-f53f-44fe-8d8e-7bee9e9148f7.jpg)
![Screenshot_2022-10-05-22-59-23-49](https://user-images.githubusercontent.com/96869052/194094330-0e534f3f-53ff-4ace-a26f-448ebc8fa0ed.jpg)

**Comment by jie65535** [comment]
不清楚，可能是终端的问题，关键看配置文件里设置对了没有，试试能不能执行就知道了。

顺便，还增加了别名可以用参数的功能，像刚刚那个礼包，可以at某人来指定发给谁。
例如 `op 新手礼包 @某人` 就可以给人发了
