### ISSUE TITLE
[问题] 同步群聊消息时仅显示用户名

### ISSUE THREAD

**Issue by huoyan391** [jie65535/JGrasscutterCommand#9]
只能同步发信人昵称，无法同步内容，发信时加上say才会发出，但不是同条消息

**Comment by jie65535** [comment]
需要更多信息才能提供帮助，包括但不限于Mirai日志/Grasscutter日志等信息。

**Comment by huoyan391** [comment]
目前问题就是这样，我也不好描述
[图片1](https://img1.imgtp.com/2022/10/03/mYIBS4b2.jpg)
[图片2](https://i.imgtg.com/2022/10/03/mjeEI.jpg)
[图片3](https://i.imgtg.com/2022/10/03/mjrID.jpg)

**Comment by jie65535** [comment]
我知道了，好像是把换行当成多条命令来执行了。稍后我检查一下，谢谢反馈。

**Comment by jie65535** [comment]
https://github.com/jie65535/JGrasscutterCommand/releases/tag/v0.4.0

现已发布更新，邀请您协助测试新版本功能，并将测试结果在下方回复，谢谢！

**Comment by huoyan391** [comment]
同步时一直同步消息失败

**Comment by huoyan391** [comment]
功能正常
